backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "homepage"
    label: "Thuispagina"
    folder: "pages/homepage"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Subtitel", name: "subtitle", widget: "string" }
      - { label: "Loungefest Datum", name: "loungefest_date", widget: "string" }
      - { label: "Youtube link", name: "youtube", widget: "string" }
      - { label: "Knop tekst", name: "button_title", widget: "string" }
      - { label: "Knop link", name: "button_link", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
  # Our blog posts
  - name: "nieuws" # Used in routes, e.g., /admin/collections/blog
    label: "Nieuws" # Used in the UI
    folder: "nieuws" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  #Informatie
  - name: "info"
    label: "Info"
    folder: "info"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
  - name: "artist"
    label: "Artiest"
    folder: "artist"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Naam", name: "name", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Dag", name: "day", widget: "string" }
      - { label: "Tijd", name: "time", widget: "string" }
      - { label: "Youtube", name: "youtube", widget: "string" }
      - label: "Plaatje"
        name: "image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "ploegen"
    label: "Ploegen"
    folder: "ploegen"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
  - name: "over-ons"
    label: "Over Ons"
    folder: "pages/over-ons"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Vrijwilligers titel", name: "vrijwilligers_title", widget: "string" }
      - { label: "Vrijwilligers body", name: "vrijwilligers_body", widget: "markdown" }
      - { label: "Ploegen titel", name: "ploegen_title", widget: "string" }
      - { label: "Ploegen body", name: "ploegen_body", widget: "markdown" }
      - { label: "Organisatie titel", name: "organisatie_title", widget: "string" }
      - { label: "Organisatie body", name: "organisatie_body", widget: "markdown" }
      - { label: "Edities titel", name: "edities_title", widget: "string" }
      - { label: "Edities body", name: "edities_body", widget: "markdown" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }